### ISSUE TITLE
External QPS reader

### ISSUE THREAD

**Issue by mtanneau** [mtanneau/SMPSReader.jl#1]
Waiting for update on https://github.com/JuliaSmoothOptimizers/QPSReader.jl/issues/11 so we don't need to re-write an MPS parser.

**Comment by odow** [comment]
Is there any reason to not depend upon MOI and just use the MOI.FileFormats.MPS reader?

**Comment by mtanneau** [comment]
The main issue with depending on MOI (besides performance, which isn't a real issue anyway) is that any change to the MPS reader, e.g., to support Free MPS format, or quadratic terms, would be contingent on making a new MOI release.

**Comment by odow** [comment]
We can upstream patch releases of MOI with these changes. The reader should support free and fixed, but it probably isn't well tested. QP terms are annoying due to different MPS implementations, e.g., Gurobi != MOSEK.
